// <auto-generated />
using System;
using LectureSchedulingAndAnalysingPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LectureSchedulingAndAnalysingPlatform.Migrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20210323101746_subject halls database update")]
    partial class subjecthallsdatabaseupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("ApprovedById1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById1");

                    b.HasIndex("PermissionId");

                    b.ToTable("A");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Electrical and Information Engineering Department Building"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Name = "Civil and Environment Engineering Engineering Department Building"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Name = "Mechanical and Manufacturing Engineering Department Building"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Administration Building"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lecture Hall"
                        });
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EIE",
                            Name = "Electrical and Information Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CEE",
                            Name = "Civil and Environment Engineering"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MME",
                            Name = "Mechanical and Manufacturing Engineering"
                        },
                        new
                        {
                            Id = 4,
                            Code = "IS",
                            Name = "Interdisciplinary Studies"
                        });
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 5,
                            Name = "DO1-A",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 5,
                            Name = "DO1-B",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 5,
                            Name = " DO2-A ",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 5,
                            Name = " DO2-B",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = 5,
                            Name = "LR1",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 6,
                            BuildingId = 5,
                            Name = "LR2",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 7,
                            BuildingId = 5,
                            Name = "LT1",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 8,
                            BuildingId = 5,
                            Name = "LT2",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 9,
                            BuildingId = 5,
                            Name = "NLH1",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 10,
                            BuildingId = 5,
                            Name = "NLH2",
                            PermissionType = "null"
                        },
                        new
                        {
                            Id = 11,
                            BuildingId = 4,
                            Name = "IS-CC",
                            PermissionType = "isHOD"
                        },
                        new
                        {
                            Id = 12,
                            BuildingId = 1,
                            Name = "ELEC-CC",
                            PermissionType = "elecHOD"
                        },
                        new
                        {
                            Id = 13,
                            BuildingId = 1,
                            Name = "ELR",
                            PermissionType = " elecHOD "
                        },
                        new
                        {
                            Id = 14,
                            BuildingId = 2,
                            Name = "CLR",
                            PermissionType = "civilHOD"
                        },
                        new
                        {
                            Id = 15,
                            BuildingId = 3,
                            Name = "MLR",
                            PermissionType = "mechHOD"
                        },
                        new
                        {
                            Id = 16,
                            BuildingId = 4,
                            Name = " IS-Seminor ",
                            PermissionType = "isHOD"
                        });
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Hod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Hods");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Permitted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PermittedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PermittedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("[SessionId] IS NOT NULL");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.PermissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ar")
                        .HasColumnType("bit");

                    b.Property<bool>("Hod")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ar = false,
                            Hod = false,
                            Name = "Lecture Hall Building"
                        },
                        new
                        {
                            Id = 2,
                            Ar = false,
                            Hod = true,
                            Name = "Department Building"
                        },
                        new
                        {
                            Id = 3,
                            Ar = true,
                            Hod = false,
                            Name = "Administration Building"
                        },
                        new
                        {
                            Id = 4,
                            Ar = true,
                            Hod = false,
                            Name = "Auditorium"
                        });
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HallId")
                        .HasColumnType("int");

                    b.Property<bool>("Permitted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HallId")
                        .IsUnique()
                        .HasFilter("[HallId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Reserver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservers");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HallId")
                        .HasColumnType("int");

                    b.Property<bool>("Permitted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CE1301",
                            Name = "Introduction to Civil Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CE2302",
                            Name = "Mechanics of Materials"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CE2201",
                            Name = "Fundamentals of Fluid Mechanics"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CE3301",
                            Name = "Building Planning and Cost Estimating"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CE3202",
                            Name = "Concrete Technology"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CE3203",
                            Name = "Engineering Surveying"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CE3304",
                            Name = "Fluid Mechanics"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CE3205",
                            Name = "Structural Analysis I"
                        },
                        new
                        {
                            Id = 9,
                            Code = "CE4301",
                            Name = "Design of Concrete Structures I"
                        },
                        new
                        {
                            Id = 10,
                            Code = "CE4302",
                            Name = "Engineering Geology and Soil Mechanics"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CE4203",
                            Name = "Structural Analysis II"
                        },
                        new
                        {
                            Id = 12,
                            Code = "CE4304",
                            Name = "Transportation Engineering"
                        },
                        new
                        {
                            Id = 13,
                            Code = "CE4305",
                            Name = "Water and Wastewater Engineering CE4305"
                        },
                        new
                        {
                            Id = 14,
                            Code = "CE5201",
                            Name = "Design of Steel Structures"
                        },
                        new
                        {
                            Id = 15,
                            Code = "CE5302",
                            Name = "Highway Engineering Design"
                        },
                        new
                        {
                            Id = 16,
                            Code = "CE5303",
                            Name = "Hydraulic Engineering"
                        },
                        new
                        {
                            Id = 17,
                            Code = "CE5204",
                            Name = "Structural Analysis III"
                        },
                        new
                        {
                            Id = 18,
                            Code = "CE5251",
                            Name = "Design of Timber and Masonry Structures (TE)"
                        },
                        new
                        {
                            Id = 19,
                            Code = "CE5252",
                            Name = "Graphical User Interface Programming (TE)"
                        },
                        new
                        {
                            Id = 20,
                            Code = "CE5253",
                            Name = "Infrastructure Planning (TE)"
                        },
                        new
                        {
                            Id = 21,
                            Code = "CE5254",
                            Name = "Integrated Solid Waste Management (TE)"
                        },
                        new
                        {
                            Id = 22,
                            Code = "CE5255",
                            Name = "Remote Sensing and GIS (TE)"
                        },
                        new
                        {
                            Id = 23,
                            Code = "CE6301",
                            Name = "Construction Processes and Technology"
                        },
                        new
                        {
                            Id = 24,
                            Code = "CE6302",
                            Name = "Design of Concrete structures II"
                        },
                        new
                        {
                            Id = 25,
                            Code = "CE6303",
                            Name = "Engineering Hydrology"
                        },
                        new
                        {
                            Id = 26,
                            Code = "CE6304",
                            Name = "Environmental Engineering Design"
                        },
                        new
                        {
                            Id = 27,
                            Code = "CE6305",
                            Name = "Geotechnical Engineering"
                        },
                        new
                        {
                            Id = 28,
                            Code = "CE6106",
                            Name = "Surveying Work Camp"
                        },
                        new
                        {
                            Id = 29,
                            Code = "CE6251",
                            Name = "Building Services Engineering (TE)"
                        },
                        new
                        {
                            Id = 30,
                            Code = "CE6252",
                            Name = "Dynamic & Control of Structures (TE)"
                        },
                        new
                        {
                            Id = 31,
                            Code = "CE6253",
                            Name = "Ecological Engineering (TE)"
                        },
                        new
                        {
                            Id = 32,
                            Code = "CE6254",
                            Name = "Coastal Engineering (TE)"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CE7301",
                            Name = "Construction Management"
                        },
                        new
                        {
                            Id = 34,
                            Code = "CE7402",
                            Name = "Comprehensive Design Project"
                        },
                        new
                        {
                            Id = 35,
                            Code = "CE7203",
                            Name = "Computer Analysis of Structures"
                        },
                        new
                        {
                            Id = 36,
                            Code = "CE7304",
                            Name = "Environmental Management"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CE7305",
                            Name = "Geotechnical Engineering Design"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CE7206",
                            Name = "Introduction to Research Methodology"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CE7607",
                            Name = "Undergraduate Research Project"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CE7251",
                            Name = "Coastal Engineering – Application and Management (TE)"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CE7252",
                            Name = "Ground Improvement Techniques (TE)"
                        },
                        new
                        {
                            Id = 42,
                            Code = "CE7253",
                            Name = "Highway Maintenance and Management (TE)"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CE7254",
                            Name = "Water Reclamation and Reuse (TE)"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CE8252",
                            Name = "Irrigation and Watershed Management (TE)"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CE8253",
                            Name = "Water Resource Planning and Management (TE)"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CE8254",
                            Name = "Analysis and Design of Large Structures for Dynamic Loadings (TE)"
                        },
                        new
                        {
                            Id = 47,
                            Code = "EE1102",
                            Name = "Introduction to Programming"
                        },
                        new
                        {
                            Id = 48,
                            Code = "EE2201",
                            Name = "Object Oriented Programming"
                        },
                        new
                        {
                            Id = 49,
                            Code = "EE2202",
                            Name = "Introduction to Electronic Engineering"
                        },
                        new
                        {
                            Id = 50,
                            Code = "EE3301",
                            Name = "Analog Electronics"
                        },
                        new
                        {
                            Id = 51,
                            Code = "EE3302",
                            Name = "Engineering Electromagnetism"
                        },
                        new
                        {
                            Id = 52,
                            Code = "EE3303",
                            Name = "Electric Machines"
                        },
                        new
                        {
                            Id = 53,
                            Code = "EE3204",
                            Name = "Graphical User Interface Programming"
                        },
                        new
                        {
                            Id = 54,
                            Code = "EE3205",
                            Name = "Signals and Systems"
                        },
                        new
                        {
                            Id = 55,
                            Code = "EE3207",
                            Name = "Planning and Management for Electrical Engineers (TE)"
                        },
                        new
                        {
                            Id = 56,
                            Code = "EE3108",
                            Name = "Electronic Project"
                        },
                        new
                        {
                            Id = 57,
                            Code = "EE4301",
                            Name = "Communication Theory"
                        },
                        new
                        {
                            Id = 58,
                            Code = "EE4302",
                            Name = "Digital Electronics"
                        },
                        new
                        {
                            Id = 59,
                            Code = "EE4303",
                            Name = "Data Structures and Algorithms"
                        },
                        new
                        {
                            Id = 60,
                            Code = "EE4204",
                            Name = "Electrical and Electronic Measurements"
                        },
                        new
                        {
                            Id = 61,
                            Code = "EE4305",
                            Name = "Power Systems"
                        },
                        new
                        {
                            Id = 62,
                            Code = "EE4106",
                            Name = "Software Engineering Principles"
                        },
                        new
                        {
                            Id = 63,
                            Code = "EE5201",
                            Name = "Computer Architecture"
                        },
                        new
                        {
                            Id = 64,
                            Code = "EE5302",
                            Name = "Computer Networks"
                        },
                        new
                        {
                            Id = 65,
                            Code = "EE5203",
                            Name = "Data Management Systems"
                        },
                        new
                        {
                            Id = 66,
                            Code = "EE5304",
                            Name = "Power Electronics"
                        },
                        new
                        {
                            Id = 67,
                            Code = "EE5305",
                            Name = "Sensors, Transducers and Measurement Techniques"
                        },
                        new
                        {
                            Id = 68,
                            Code = "EE5206",
                            Name = "Software Project"
                        },
                        new
                        {
                            Id = 69,
                            Code = "EE5207",
                            Name = "Internet Technologies (TE)"
                        },
                        new
                        {
                            Id = 70,
                            Code = "EE5208",
                            Name = "Electronic Circuit Design (TE)"
                        },
                        new
                        {
                            Id = 71,
                            Code = "EE6301",
                            Name = "Communication Systems"
                        },
                        new
                        {
                            Id = 72,
                            Code = "EE6302",
                            Name = "Control System Design"
                        },
                        new
                        {
                            Id = 73,
                            Code = "EE6303",
                            Name = "Electric Machines and Drives"
                        },
                        new
                        {
                            Id = 74,
                            Code = "EE6304",
                            Name = "Embedded System Design"
                        },
                        new
                        {
                            Id = 75,
                            Code = "EE6205",
                            Name = "Energy and Environment"
                        },
                        new
                        {
                            Id = 76,
                            Code = "EE6206",
                            Name = "Operating Systems Programming (TE)"
                        },
                        new
                        {
                            Id = 77,
                            Code = "EE6207",
                            Name = "Wireless and Mobile Communication (TE)"
                        },
                        new
                        {
                            Id = 78,
                            Code = "EE7601",
                            Name = "Undergraduate Project"
                        },
                        new
                        {
                            Id = 79,
                            Code = "EE7202",
                            Name = "Power Electronic Applications (TE)"
                        },
                        new
                        {
                            Id = 80,
                            Code = "EE7203",
                            Name = "Power System Analysis (TE)"
                        },
                        new
                        {
                            Id = 81,
                            Code = "EE7204",
                            Name = "Scientific Computing (TE)"
                        },
                        new
                        {
                            Id = 82,
                            Code = "EE7205",
                            Name = "Object Oriented Design Patterns and Principles (TE)"
                        },
                        new
                        {
                            Id = 83,
                            Code = "EE7206",
                            Name = "Mobile Application Development (TE)"
                        },
                        new
                        {
                            Id = 84,
                            Code = "EE7206",
                            Name = "Machine Learning (TE)"
                        },
                        new
                        {
                            Id = 85,
                            Code = "EE7207",
                            Name = "Computer Vision and Image Processing (TE)"
                        },
                        new
                        {
                            Id = 86,
                            Code = "EE7208",
                            Name = "Advanced Data Communication (TE)"
                        },
                        new
                        {
                            Id = 87,
                            Code = "EE7209",
                            Name = "Digital Signal Processing (TE)"
                        },
                        new
                        {
                            Id = 88,
                            Code = "EE7210",
                            Name = "Telecommunication Networks (TE)"
                        },
                        new
                        {
                            Id = 89,
                            Code = "EE7211",
                            Name = "Optical Fiber Communication (TE)"
                        },
                        new
                        {
                            Id = 90,
                            Code = "EE7212",
                            Name = "EE 7212 Introduction to Research (TE)"
                        },
                        new
                        {
                            Id = 91,
                            Code = "EE8301",
                            Name = "High Voltage Engineering (TE)"
                        },
                        new
                        {
                            Id = 92,
                            Code = "EE8202",
                            Name = "Electrical Systems in Buildings (TE)"
                        },
                        new
                        {
                            Id = 93,
                            Code = "EE8203",
                            Name = "High Performance Computing (TE)"
                        },
                        new
                        {
                            Id = 94,
                            Code = "EE8204",
                            Name = "Information Security (TE)"
                        },
                        new
                        {
                            Id = 95,
                            Code = "EE8205 ",
                            Name = "Software Architecture (TE)"
                        },
                        new
                        {
                            Id = 96,
                            Code = "EE8206 ",
                            Name = "Computer Graphics (TE)"
                        },
                        new
                        {
                            Id = 97,
                            Code = "EE8207 ",
                            Name = "Optimization Techniques for Engineers (TE)"
                        },
                        new
                        {
                            Id = 98,
                            Code = "EE8208",
                            Name = "Intelligent Systems Design (TE)"
                        },
                        new
                        {
                            Id = 99,
                            Code = "EE8209",
                            Name = "Microwave Communications (TE)"
                        },
                        new
                        {
                            Id = 100,
                            Code = "EE8210",
                            Name = "Digital Communication (TE)"
                        },
                        new
                        {
                            Id = 101,
                            Code = "EE8211",
                            Name = "Design and Management of Data Networks (TE)"
                        },
                        new
                        {
                            Id = 102,
                            Code = "EE8212",
                            Name = "Biomedical Engineering (TE)"
                        },
                        new
                        {
                            Id = 103,
                            Code = "EE8213",
                            Name = "Photonic Devices (TE)"
                        },
                        new
                        {
                            Id = 104,
                            Code = "EE8115",
                            Name = "Introduction to Hardware Description Languages (TE)"
                        },
                        new
                        {
                            Id = 105,
                            Code = "EE8117",
                            Name = "Video Compression and Communication (TE)"
                        },
                        new
                        {
                            Id = 106,
                            Code = "ME1202",
                            Name = "Fundamentals of Engineering Thermodynamics"
                        },
                        new
                        {
                            Id = 107,
                            Code = "ME2302",
                            Name = "Introduction to Materials Science and Manufacturing Engineering"
                        },
                        new
                        {
                            Id = 108,
                            Code = "ME3301",
                            Name = "Fluid Mechanics"
                        },
                        new
                        {
                            Id = 109,
                            Code = "ME3302",
                            Name = "Metallurgy for Engineers"
                        },
                        new
                        {
                            Id = 110,
                            Code = "ME3303",
                            Name = "Modelling of Dynamic Systems"
                        },
                        new
                        {
                            Id = 111,
                            Code = "ME3304",
                            Name = "Strength of Materials"
                        },
                        new
                        {
                            Id = 112,
                            Code = "ME3111",
                            Name = "Engineering Design Methodology (TE)"
                        },
                        new
                        {
                            Id = 113,
                            Code = "ME4301",
                            Name = "Applied Thermodynamics"
                        },
                        new
                        {
                            Id = 114,
                            Code = "ME4302",
                            Name = "Design of Machine Elements"
                        },
                        new
                        {
                            Id = 115,
                            Code = "ME4303",
                            Name = "Manufacturing Engineering"
                        },
                        new
                        {
                            Id = 116,
                            Code = "ME4304",
                            Name = "Mechanics of Machines"
                        },
                        new
                        {
                            Id = 117,
                            Code = "ME4311",
                            Name = "Analog and Digital Electronics (TE)"
                        },
                        new
                        {
                            Id = 118,
                            Code = "ME4312",
                            Name = "Automobile Engineering (TE)"
                        },
                        new
                        {
                            Id = 119,
                            Code = "ME5301",
                            Name = "Computer Aided Design"
                        },
                        new
                        {
                            Id = 120,
                            Code = "ME5302",
                            Name = "Electrical Power and Machines"
                        },
                        new
                        {
                            Id = 121,
                            Code = "ME5303",
                            Name = "Mechanical Engineering Design"
                        },
                        new
                        {
                            Id = 122,
                            Code = "ME5304",
                            Name = "Refrigeration and Air Conditioning"
                        },
                        new
                        {
                            Id = 123,
                            Code = "ME5311",
                            Name = "Mechatronics (TE)"
                        },
                        new
                        {
                            Id = 124,
                            Code = "ME5312",
                            Name = "Marine Engineering Knowledge (TE)"
                        },
                        new
                        {
                            Id = 125,
                            Code = "ME5113",
                            Name = "Technical Report Writing (TE)"
                        },
                        new
                        {
                            Id = 126,
                            Code = "ME5214",
                            Name = "Advanced Automobile Engineering (TE)"
                        },
                        new
                        {
                            Id = 127,
                            Code = "ME6301",
                            Name = "Advanced Fluid Mechanics"
                        },
                        new
                        {
                            Id = 128,
                            Code = "ME6302",
                            Name = "Automatic Control Engineering"
                        },
                        new
                        {
                            Id = 129,
                            Code = "ME6303",
                            Name = "Computer Aided Manufacturing"
                        },
                        new
                        {
                            Id = 130,
                            Code = "ME6304",
                            Name = "Production Planning and control"
                        },
                        new
                        {
                            Id = 131,
                            Code = "ME6211",
                            Name = "Nanotechnology (TE)"
                        },
                        new
                        {
                            Id = 132,
                            Code = "ME6312",
                            Name = "Robotics (TE)"
                        },
                        new
                        {
                            Id = 133,
                            Code = "ME6213",
                            Name = "Research Methodology and Ethics (TE)"
                        },
                        new
                        {
                            Id = 134,
                            Code = "ME6114",
                            Name = "Technical Presentation Skills (TE)"
                        },
                        new
                        {
                            Id = 135,
                            Code = "ME7301",
                            Name = "Maintenance Management"
                        },
                        new
                        {
                            Id = 136,
                            Code = "ME7302",
                            Name = "Production and Operations Management"
                        },
                        new
                        {
                            Id = 137,
                            Code = "ME7303",
                            Name = "Solid Mechanics "
                        },
                        new
                        {
                            Id = 138,
                            Code = "ME7604",
                            Name = "Undergraduate Project"
                        },
                        new
                        {
                            Id = 139,
                            Code = "ME7311",
                            Name = "Advanced Marine Engineering (TE)"
                        },
                        new
                        {
                            Id = 140,
                            Code = "ME7312",
                            Name = "Energy Technology (TE)"
                        },
                        new
                        {
                            Id = 141,
                            Code = "ME7313",
                            Name = "Industrial Automation and Control (TE)"
                        },
                        new
                        {
                            Id = 142,
                            Code = "ME7314",
                            Name = "Polymer Technology (TE)"
                        },
                        new
                        {
                            Id = 143,
                            Code = "ME8301",
                            Name = "Heat Transfer"
                        },
                        new
                        {
                            Id = 144,
                            Code = "ME8302",
                            Name = "Industrial Fluid Dynamics"
                        },
                        new
                        {
                            Id = 145,
                            Code = "ME8311",
                            Name = "Aerospace Engineering (TE)"
                        },
                        new
                        {
                            Id = 146,
                            Code = "ME8312",
                            Name = "Energy Management (TE)"
                        },
                        new
                        {
                            Id = 147,
                            Code = "EE8212",
                            Name = "Biomedical Engineering (TE)"
                        },
                        new
                        {
                            Id = 148,
                            Code = "ME8213",
                            Name = "Individual Research Project (TE)"
                        },
                        new
                        {
                            Id = 149,
                            Code = "IS1302",
                            Name = "Communication for Engineers"
                        },
                        new
                        {
                            Id = 150,
                            Code = "IS1401",
                            Name = "Mathematical Fundamentals for Engineers"
                        },
                        new
                        {
                            Id = 151,
                            Code = "IS2401",
                            Name = "Linear Algebra and Differential Equations"
                        },
                        new
                        {
                            Id = 152,
                            Code = "IS3301",
                            Name = "Complex Analysis and Mathematical Transforms"
                        },
                        new
                        {
                            Id = 153,
                            Code = "IS3302",
                            Name = "Society and the Engineer (GE)"
                        },
                        new
                        {
                            Id = 154,
                            Code = "IS3303",
                            Name = "Basic Economics (GE)"
                        },
                        new
                        {
                            Id = 155,
                            Code = "IS3104",
                            Name = "Graphic Design (GE)"
                        },
                        new
                        {
                            Id = 156,
                            Code = "IS3105",
                            Name = "Creative Dance and Oriental Ballet (GE)"
                        },
                        new
                        {
                            Id = 157,
                            Code = "IS3206",
                            Name = "Physical Development and Health Management (GE)"
                        },
                        new
                        {
                            Id = 158,
                            Code = "IS3207",
                            Name = "Introduction to Astronomy (GE)"
                        },
                        new
                        {
                            Id = 159,
                            Code = "IS4301",
                            Name = "Probability and Statistics"
                        },
                        new
                        {
                            Id = 160,
                            Code = "IS4302",
                            Name = "Technology and Society (GE)"
                        },
                        new
                        {
                            Id = 161,
                            Code = "IS4103",
                            Name = "Appreciation of Music (GE)"
                        },
                        new
                        {
                            Id = 162,
                            Code = "IS4104",
                            Name = "Digital Modelling and Animation (GE)"
                        },
                        new
                        {
                            Id = 163,
                            Code = "IS4205",
                            Name = "Aesthetics and Design (GE)"
                        },
                        new
                        {
                            Id = 164,
                            Code = "IS4106",
                            Name = "Spiritual Development (GE)"
                        },
                        new
                        {
                            Id = 165,
                            Code = "IS5301",
                            Name = "Numerical Methods"
                        },
                        new
                        {
                            Id = 166,
                            Code = "IS5202",
                            Name = "Industrial Safety and Resource Management (GE)"
                        },
                        new
                        {
                            Id = 167,
                            Code = "IS5303",
                            Name = "Financial Management (GE)"
                        },
                        new
                        {
                            Id = 168,
                            Code = "IS5304",
                            Name = "Industrial Management (GE)"
                        },
                        new
                        {
                            Id = 169,
                            Code = "IS5205",
                            Name = "Information Literacy and Scientific Communication Skills (GE)"
                        },
                        new
                        {
                            Id = 170,
                            Code = "IS6301",
                            Name = "Mathematical Modelling "
                        },
                        new
                        {
                            Id = 171,
                            Code = "IS6202",
                            Name = "Introduction to Sociology (GE)"
                        },
                        new
                        {
                            Id = 172,
                            Code = "IS6203",
                            Name = "Entrepreneurship and Project Management (GE)"
                        },
                        new
                        {
                            Id = 173,
                            Code = "IS6304",
                            Name = "Management and Organizational Behavior (GE)"
                        },
                        new
                        {
                            Id = 174,
                            Code = "IS7101",
                            Name = "Engineering Ethics (GE)"
                        },
                        new
                        {
                            Id = 175,
                            Code = "IS8201",
                            Name = "English for the Professional World (GE)"
                        });
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.SubjectUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("SubjectUsers");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "34d2c848-ce0b-45ad-9902-1969b54ff7d8",
                            ConcurrencyStamp = "6239cc49-6703-4c63-a2f4-03f7972433de",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "1c73d407-cc71-487a-98ca-01b852d4aa76",
                            ConcurrencyStamp = "7342e931-7a4d-40b2-8908-6f144c98b349",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "93c52557-5798-46e8-9e80-16a44a6e9267",
                            ConcurrencyStamp = "de0e9942-18e1-48dc-bba1-d34be592c793",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7269c841-7064-43f0-a5b6-228a1820405f",
                            ConcurrencyStamp = "5fe27e68-0395-4180-9e68-24bbe2441705",
                            Name = "AR",
                            NormalizedName = "AR"
                        },
                        new
                        {
                            Id = "b6046ef1-68ec-4946-b6ae-136e89d4a02a",
                            ConcurrencyStamp = "77e5c074-b95a-40e6-8dc4-a8e2e4dbd309",
                            Name = "HOD",
                            NormalizedName = "HOD"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("IdentityUserRole<string>");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Approval", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById1");

                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Permission", "Permission")
                        .WithMany("Approvals")
                        .HasForeignKey("PermissionId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Building", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Department", "Department")
                        .WithMany("Buildings")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Hall", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Building", "Building")
                        .WithMany("Halls")
                        .HasForeignKey("BuildingId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Hod", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Department", "Department")
                        .WithOne("Hod")
                        .HasForeignKey("LectureSchedulingAndAnalysingPlatform.Models.Hod", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.User", "User")
                        .WithOne("Hod")
                        .HasForeignKey("LectureSchedulingAndAnalysingPlatform.Models.Hod", "UserId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Permission", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Session", "Session")
                        .WithOne("Permission")
                        .HasForeignKey("LectureSchedulingAndAnalysingPlatform.Models.Permission", "SessionId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Reservation", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Hall", "Hall")
                        .WithOne("Reservation")
                        .HasForeignKey("LectureSchedulingAndAnalysingPlatform.Models.Reservation", "HallId");

                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Reserver", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId");

                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.Session", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Hall", "Hall")
                        .WithMany("Sessions")
                        .HasForeignKey("HallId");

                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Subject", "Subject")
                        .WithMany("Sessions")
                        .HasForeignKey("SubjectId");

                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.SubjectUser", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Subject", "Subject")
                        .WithMany("SubjectUsers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.User", "User")
                        .WithMany("SubjectUsers")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LectureSchedulingAndAnalysingPlatform.Models.User", b =>
                {
                    b.HasOne("LectureSchedulingAndAnalysingPlatform.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
